### ISSUE TITLE
Contributing to party.io

### ISSUE THREAD

**Issue by Aslemammad** [partykit/partykit#124]
I wanted to ask if this is something WIP (privately) or if there's a chance contributors can pick it up and work on it in a PR. Thanks for the amazing lib.

**Comment by threepointone** [comment]
Hello! I definitely want contributors here, but I would love to make a basic version of it first before having other folks work on it. I'll leave this issue open and ping you!

**Comment by Aslemammad** [comment]
Thank you so much, yea, I wanted to put time on it, but if you do, it would
be better.

**Comment by nitishmittal1990** [comment]
@threepointone I would also love to contribute, waiting for the update.

**Comment by threepointone** [comment]
We have since landed party.io (experimental for now) a fully compatible socket io backend for partykit https://www.npmjs.com/package/party.io

Closing this issue
