### ISSUE TITLE
Using recommended-requiring-type-checking from typescript-eslint

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [partykit/partykit#125]
👋 congrats on open sourcing!

I see you're already using a bunch of rules from typescript-eslint: https://github.com/partykit/partykit/blob/baa74442a567b303ef0f93edcf3baa6622e0a749/.eslintrc.js. Great!

We actually have more rules available: https://typescript-eslint.io/linting/configs#recommended-requiring-type-checking. Right now, you're using `plugin:@typescript-eslint/recommended` but not ` plugin:@typescript-eslint/recommended-requiring-type-checking`. The latter enables quite a few useful rules -including `no-floating-promises`. Would you be up for me sending a PR enabling more for you? 😄

**Comment by threepointone** [comment]
hell yeah, I'd open to a PR. does it get much slower with those rules?

**Comment by JoshuaKGoldberg** [comment]
[Linting can get a little slower, yeah](https://typescript-eslint.io/linting/typed-linting#how-is-performance). But the "good" news is you already enable typed linting for rules such as [`@typescript-eslint/no-floating-promises`](https://typescript-eslint.io/rules/no-floating-promises) - so you're already incurring some of that penalty! 🙌 

I'll post a perf comparison in a PR. Thanks!
