### ISSUE TITLE
Examples do not work on Windows.

### ISSUE THREAD

**Issue by DevMaxC** [partykit/partykit#165]
Many of the examples do not work on windows ( I have only tested basic, monaco and yjs ).

**Comment by DevMaxC** [comment]
After trying out some fixes, it appears that the Basic example has most issues cleared up by including partykit and partysocket in the dependencies. However still getting the following issue:
![image](https://github.com/partykit/partykit/assets/20259746/3e9f447c-390c-4055-825e-8bc91425d5ec)

**Comment by threepointone** [comment]
you shouldn't have to include those dependencies, try running  `npm install` in the root dir which should setup npm workspaces and make those packages available. I think I know what the other issue in the screenshot is, lemme fix that asap

**Comment by threepointone** [comment]
landed a bunch of improvements in https://github.com/partykit/partykit/pull/169, they might unblock you

**Comment by threepointone** [comment]
Closing this, happy to reopen is the problems persist
