### ISSUE TITLE
A plan to fix flaky partysocket tests

### ISSUE THREAD

**Issue by tom-sherman** [partykit/partykit#173]
Here's my proposed changes:

- Create only one server for the entire suite. I don't think there's any value in trying to recreate the server. This would solve the EADDRINUSE issue
- Use JSDOMs WebSocket client implementation, not the one imported one from `ws`. JSDOM is probs using this lib under the hood, but I assume it does some work to make it more realistic. This unblocks #172
- Explicitly close websocket clients on test failure. Not sure how best to do this, would be relatively simple with [`using`](https://www.totaltypescript.com/typescript-5-2-new-keyword-using) but without that we probably needs to wrap every assertion like `try { assert() } finally { ws.close() }`

I'm relatively confident this should fix the flakiness, thoughts?

**Comment by threepointone** [comment]
This sounds dope, I approve. Would you like a crack at it?

**Comment by tom-sherman** [comment]
Already started my friend!

**Comment by threepointone** [comment]
You’re amazing, thank you!

**Comment by threepointone** [comment]
I just disabled running tests on windows/mac, they seem to be particularly flaky
