### ISSUE TITLE
make a react-native specific build for `partysocket`

### ISSUE THREAD

**Issue by threepointone** [partykit/partykit#232]
react-native doesn't have EventTarget, so we should bundle a shim and provide it in the package

**Comment by technoplato** [comment]
@threepointone Was this completed?


I'm trying to run stately-sky v0.0.4 and running into this error:

![simulator_screenshot_8ACCF467-0BED-4291-A44C-DD21FDDE729C](https://github.com/partykit/partykit/assets/6922904/e01ddda8-415f-40a7-87a8-e176cce350f3)

<details><summary>relevant source</summary>
<p>

```
import { useStatelyActor } from '@statelyai/sky-react';
import { skyConfig } from './lights.sky';

const skyurl = 'https://sky.stately.ai/5hIBJk';
const sessionKey = 'shared';

export const useFoo = () => {
  const [snapshot, send, actor] = useStatelyActor(
    {
      apiKey: 'sta_e922f7a4-809c-4eb0-8311-0a1142dd3c57',
      url: skyurl,
      sessionId: sessionKey,
    },
    skyConfig
  );

  // const [state, setState] = React.useState(0);

  // return [state, setState];

  return [snapshot, send, actor];
};

```

<details><summary>machine</summary>
```
// This file was generated by the XState CLI, please do not edit it manually.
import { createMachine } from 'xstate';

const machine = createMachine(
  {
    context: {
      timer: 0,
    },
    id: 'Traffic Light',
    initial: 'green',
    states: {
      green: {
        description: 'The light is green. Cars can proceed safely.',
        on: {
          'Change to yellow': {
            target: 'yellow',
          },
        },
      },
      yellow: {
        description: 'The light is yellow. Cars should prepare to stop.',
        on: {
          'Change to red': {
            target: 'red',
          },
        },
      },
      red: {
        description: 'The light is red. Cars should stop.',
        on: {
          'Change to green': {
            target: 'green',
          },
        },
      },
    },
    types: {
      events: {} as
        | { type: 'Change to red' }
        | { type: 'Change to green' }
        | { type: 'Change to yellow' },
      context: {} as { timer: number },
    },
  },
  {
    actions: {},
    actors: {},
    guards: {},
    delays: {},
  }
);
export const skyConfig = {
  actorId: '461ab995-e697-4069-b807-16f3a19607b1',
  machine,
};

```
<p>

<details><summary>package.json</summary>
<p>

{
  "name": "@knoware/source",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "nx:graph": "npx nx graph",
    "nx:graph:json": "npx nx graph --file=project.graph.json",
    "watchman:fix": "watchman watch-del '/Users/michael.lustig/Development/personal/knoware-project-container/knoware' ; watchman watch-project '/Users/michael.lustig/Development/personal/knoware-project-container/knoware'",
    "start:mobile": "npx nx start mobile",
    "run:android": "npx nx run-android mobile",
    "run:ios": "npx nx run-ios mobile"
  },
  "private": true,
  "devDependencies": {
    "@babel/core": "^7.14.5",
    "@babel/preset-react": "^7.14.5",
    "@config-plugins/detox": "~6.0.0",
    "@expo/cli": "~0.10.12",
    "@nx/detox": "17.0.0-beta.6",
    "@nx/devkit": "16.10.0",
    "@nx/eslint-plugin": "16.10.0",
    "@nx/jest": "17.0.0-beta.6",
    "@nx/js": "17.0.0-beta.6",
    "@nx/linter": "16.10.0",
    "@nx/next": "^16.10.0",
    "@nx/playwright": "16.10.0",
    "@nx/react": "16.10.0",
    "@nx/react-native": "^16.10.0",
    "@nx/vite": "16.10.0",
    "@nx/workspace": "16.10.0",
    "@playwright/test": "^1.36.0",
    "@react-native-community/cli": "11.3.6",
    "@react-native-community/cli-platform-android": "11.3.6",
    "@react-native-community/cli-platform-ios": "11.3.6",
    "@react-native/metro-config": "^0.72.11",
    "@swc-node/register": "~1.6.7",
    "@swc/core": "~1.3.85",
    "@swc/plugin-styled-components": "^1.5.67",
    "@testing-library/jest-dom": "5.16.5",
    "@testing-library/jest-native": "~5.4.3",
    "@testing-library/react": "14.0.0",
    "@testing-library/react-native": "~12.3.0",
    "@types/jest": "^29.4.0",
    "@types/node": "18.14.4",
    "@types/react": "18.2.24",
    "@types/react-dom": "18.2.9",
    "@types/react-is": "18.2.2",
    "@types/styled-components": "5.1.26",
    "@typescript-eslint/eslint-plugin": "^5.60.1",
    "@typescript-eslint/parser": "^5.60.1",
    "@vitest/coverage-c8": "~0.32.0",
    "@vitest/ui": "~0.32.0",
    "babel-jest": "^29.4.1",
    "babel-plugin-styled-components": "1.10.7",
    "babel-preset-expo": "~9.5.2",
    "detox": "^20.11.1",
    "eas-cli": "~5.2.0",
    "eslint": "~8.46.0",
    "eslint-config-next": "13.4.1",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-import": "2.27.5",
    "eslint-plugin-jsx-a11y": "6.7.1",
    "eslint-plugin-playwright": "^0.15.3",
    "eslint-plugin-react": "7.32.2",
    "eslint-plugin-react-hooks": "4.6.0",
    "jest": "^29.4.1",
    "jest-circus": "^29.4.1",
    "jest-environment-jsdom": "^29.4.1",
    "jest-expo": "~49.0.0",
    "jest-react-native": "18.0.0",
    "metro": "0.76.7",
    "metro-babel-register": "0.76.7",
    "metro-config": "0.76.7",
    "metro-react-native-babel-preset": "0.76.7",
    "metro-react-native-babel-transformer": "0.76.7",
    "metro-resolver": "0.76.7",
    "nx": "16.10.0",
    "nx-cloud": "latest",
    "prettier": "^2.6.2",
    "react-native-svg": "13.9.0",
    "react-native-svg-transformer": "1.0.0",
    "react-test-renderer": "18.2.0",
    "ts-jest": "^29.1.0",
    "ts-node": "10.9.1",
    "typescript": "~5.1.3",
    "verdaccio": "^5.0.4",
    "vite": "~4.3.9",
    "vite-plugin-dts": "~2.3.0",
    "vitest": "~0.32.0"
  },
  "nx": {
    "includedScripts": []
  },
  "dependencies": {
    "@expo/metro-config": "~0.10.7",
    "@nx/expo": "^17.0.0-beta.6",
    "@statelyai/sky": "^0.0.4",
    "@statelyai/sky-react": "^0.0.4",
    "expo": "49.0.10",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "next": "13.4.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-is": "18.2.0",
    "react-native": "0.72.4",
    "react-native-web": "~0.19.8",
    "styled-components": "5.3.6",
    "tslib": "^2.3.0"
  }
}


</p>
</details> 


</p>
</details> 

</p>
</details>

**Comment by technoplato** [comment]
Relevant commits for timeframe: https://github.com/partykit/partykit/commits/main?after=7d0fc5c25faf09ebef10d7474806b2a73b2cab21+349&branch=main&qualified_name=refs%2Fheads%2Fmain

**Comment by technoplato** [comment]
For future travelers that want to add partykit or `stately` `sky` to their mobile projects (I've tested react-native and expo and this works), use the below code:

```

/**
 * Ensures that the necessary event shims are loaded.
 *
 * Required to use Stately Sky on React Native.
 *
 * MUST to be called at the top level of the app BEFORE `useStatelyActor` is invoked.
 * You MUST prevent any component that uses the `useState hook from being mounted before this is called.
 *
 * Required via Stately Sky -> PartySocket
 * - https://github.com/statelyai/sky/blob/main/packages/sky-core/src/actorFromStately.ts#L1
 * - Related issue from Party Kit explaining need for event-target-shim: https://github.com/partykit/partykit/issues/232
 *
 * @return {boolean} The value indicating whether the event shims are set or not.
 */
/**
 * Install `event-target-shim`
 */
import {Event, EventTarget} from 'event-target-shim';
export const useEnsureEventShimsAreLoaded = () => {
  const [shimIsSet, setShimIsSet] = React.useState(
    [globalThis.Event && globalThis.EventTarget].every(
      requiredGlobal => requiredGlobal !== undefined,
    ),
  );

  useEffect(() => {
    if (shimIsSet) {
      return;
    }

    if (!globalThis.Event) {
      globalThis.Event = Event;
    }

    if (!globalThis.EventTarget) {
      globalThis.EventTarget = EventTarget;
    }

    if (!globalThis.EventTarget || !globalThis.Event) {
      throw new Error(
        'Event Target or Event not set properly and everything is gonna suck',
      );
    }
    setShimIsSet(true);
  }, [shimIsSet]);

  return shimIsSet;
};
```

USAGE of the above code 

```
function App(): JSX.Element {
  const shimsAreLoaded = useEnsureEventShimsAreLoaded();

  const Content = shimsAreLoaded ? GoodStuff : Loading;

  return (
    <SafeAreaView>
      <View>
        <Content />
      </View>
    </SafeAreaView>
  );
}
```

NOTE that the app will crash if that hook does not return true and you attempt to invoke `useStatelyActor`

**Comment by technoplato** [comment]
> _gif or it didn't happen_

![2023-10-17 09 02 45](https://github.com/partykit/partykit/assets/6922904/ef34abe9-8604-400d-9376-562f8875f104)
