### ISSUE TITLE
y-partykit `latest` release is 0.0.0

### ISSUE THREAD

**Issue by alvarlagerlof** [partykit/partykit#235]
I tried to install y-partykit with `yarn add y-partykit` and had to figure out that the `latest` tag is 0.0.0 (probably quite old) and in fact a completely empty package except for package.json. It gets a few downloads so I recommend setting some other version as `latest` just so that installing the package without copying specific versions from one of the examples is possible.

https://www.npmjs.com/package/y-partykit?activeTab=versions

<img width="787" alt="image" src="https://github.com/partykit/partykit/assets/14835120/4323c0ec-27ed-4527-bd5a-917a08d358de">

**Comment by threepointone** [comment]
Added deprecation messages to all our packages (which should automatically disappear when we do our next release) 
<img width="626" alt="image" src="https://github.com/partykit/partykit/assets/18808/d95914e2-5d07-4488-8c03-6709919c9d3c">
<img width="557" alt="image" src="https://github.com/partykit/partykit/assets/18808/b4d90fde-48a8-4ade-b9ac-f79ef56e1291">
