### ISSUE TITLE
issue with esbuild / typeschema optional dependencies

### ISSUE THREAD

**Issue by astahmer** [partykit/partykit#254]
# context
I'm trying to use [typeschema](https://github.com/decs/typeschema) (lib that makes runtime validation library-agnostic, so the user can use zod, arktype, valibot, typebox ..) inside the partykit server

not sure why but esbuild can't skip those optional dependencies. the solution would usually be to mark them as external (as I'm not using those, only `valibot` in this example). 
I'm not aware of a way to do that (customizing partykit esbuild config) and from a quick glance I couldn't find a way either
https://github.com/partykit/partykit/blob/f60434bdc1623c38d072da9616fb8d33bb802127/packages/partykit/src/dev.tsx#L389
https://github.com/partykit/partykit/blob/f60434bdc1623c38d072da9616fb8d33bb802127/packages/partykit/src/dev.tsx#L24-L29

# minimal repro
here's the minimal repro commit: 
https://github.com/astahmer/partykit-typeschema/commit/52dc3a819be75fe4cfa0b8d77ae232f4182d0047

to run this example:
```
pnpm i && pnpm dev
```

# error
this is the error output, it stops here (= not just a warning)

```
 pnpm dev

> partykit-typeschema@1.0.0 dev /Users/astahmer/dev/reproductions/partykit-typeschema
> partykit dev src/server.ts

🎈 PartyKit v0.0.0-f60434b
---------------------------
▲ [WARNING] Serving static assets in dev mode is experimental and may change any time



✘ [ERROR] Could not resolve "fp-ts/Either"

    node_modules/.pnpm/@decs+typeschema@0.9.1_valibot@0.12.0/node_modules/@decs/typeschema/dist/io-ts-BRWJAQV3.mjs:2:24:
      2 │ import { isRight } from "fp-ts/Either";
        ╵                         ~~~~~~~~~~~~~~

  You can mark the path "fp-ts/Either" as external to exclude it from the bundle, which will remove
  this error.

✘ [ERROR] Could not resolve "yup"

    node_modules/.pnpm/@decs+typeschema@0.9.1_valibot@0.12.0/node_modules/@decs/typeschema/dist/yup-J36PHLX6.mjs:2:32:
      2 │ import { ValidationError } from "yup";
        ╵                                 ~~~~~

  You can mark the path "yup" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "@sinclair/typebox/compiler"

    node_modules/.pnpm/@decs+typeschema@0.9.1_valibot@0.12.0/node_modules/@decs/typeschema/dist/typebox-WF7VWWUM.mjs:2:29:
      2 │ import { TypeCompiler } from "@sinclair/typebox/compiler";
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@sinclair/typebox/compiler" as external to exclude it from the bundle,
  which will remove this error.

✘ [ERROR] Could not resolve "ow"

    node_modules/.pnpm/@decs+typeschema@0.9.1_valibot@0.12.0/node_modules/@decs/typeschema/dist/ow-RU2EFUAC.mjs:2:21:
      2 │ import owImport from "ow";
        ╵                      ~~~~

  You can mark the path "ow" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "@deepkit/type"

    node_modules/.pnpm/@decs+typeschema@0.9.1_valibot@0.12.0/node_modules/@decs/typeschema/dist/deepkit-KEFZXADV.mjs:2:25:
      2 │ import { validate } from "@deepkit/type";
        ╵                          ~~~~~~~~~~~~~~~

  You can mark the path "@deepkit/type" as external to exclude it from the bundle, which will remove
  this error.

```

**Comment by threepointone** [comment]
Hah, I thought this was an issue with pnpm, but even after I used npm, I notice that the `peerDependencies` listed for `@decs/typeschema` don't get installed under `node_modules`. This package is funny, no one can use it in a bundler without `external` for all the libs they don't use haha. 

Anyway, I think exposing `external` is a good idea. https://github.com/partykit/partykit/pull/255 Thanks for reporting with a repro! Could you test with the latest `partykit@beta` and lemme know whether it solves your problem?

**Comment by astahmer** [comment]
can confirm this works now ! thanks, that was fast.

on a side note, and completely unrelated to partykit, I'm not sure I can use `typeschema` anyway as it seems to lead to dts issues 😅 
> src/server/create-party-rpc.ts(48,14): error TS2742: The inferred type of 'createPartyRpc' cannot be named without a reference to '.pnpm/zod@3.22.1/node_modules/zod'. This is likely not portable. A type annotation is necessary.

> Hah, I thought this was an issue with pnpm

oh yes btw, regarding could `partykit init` command take a `--pm` flag to specify the package manager ? or I'm not sure how other tools do that install step but it felt a bit weird that it directly installed with npm (maybe asking with a prompt ?)

**Comment by threepointone** [comment]
Good idea. I think the way to do it is to detect which package manager called the command itself, and to use that to install dependencies. This was just an initial stab at the problem, we're going to polish this over the next couple of weeks for our announcement. We'll probably also make a `create-partykit` package (so you can do `npm init partykit` etc)
