### ISSUE TITLE
PartySocket's `ReconnectingWebSocket` type is treated as the `PartySocket` type

### ISSUE THREAD

**Issue by sdnts** [partykit/partykit#319]
I was trying to use PartySocket (without PartyKit though), and Typescript wasn't happy. I was able to create a minimal repro here:
https://codesandbox.io/p/sandbox/bold-flower-mtk3q2?file=/src/App.tsx:7,20

I'm not exactly sure why this is happening. TypeScript seems to think that the `WebSocket` type is the `PartySocket` type. AFAICT `ReconnectingWebSocket` class is being exported as `WebSocket`, which sounds fine to me.

Without spending a lot of brain cycles on this, I'm able to get around this issue by just exporting `ReconnectingWebSocket` directly. I've opened up a PR for it here: https://github.com/partykit/partykit/pull/318

I would be interested to learn why this is needed though if anyone knows.

**Comment by thorn0** [comment]
@sdnts `const` creates only a value declaration ([docs](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#basic-concepts)), not a type, so the type `WebSocket` in your repro is a global type from `lib.dom.d.ts`. However, when you reexport `ReconnectingWebSocket` the way you did in the PR, you reexport both the type and the value.

**Comment by sdnts** [comment]
Oh I see, that makes sense. Thanks for the explanation!
