### ISSUE TITLE
404 on Windows 11

### ISSUE THREAD

**Issue by mehdi-cit** [partykit/partykit#328]
Hi,
Got some 404 not found errors on windows for both client.js and client.css. Both files do exist but somehow are not found.
Below is the command line's console log:

```
🎈 PartyKit v0.0.7
-------------------
Build succeeded, starting server...
kj/async-io-win32.c++:982: warning: Bind address resolved to multiple addresses.  Only the first address will be used.  If this is incorrect, specify the address numerically.  This may be fixed in the future.; addrs[0].toString() = 127.0.0.1:49289
[pk:inf] Ready on http://127.0.0.1:1999 
[pk:inf] GET / 200 OK (11ms)
[pk:inf] GET /dist/client.css 404 Not Found (1ms)
[pk:inf] GET /dist/client.js 404 Not Found (2ms)
[pk:inf] GET /normalize.css 200 OK (9ms)
[pk:inf] GET /favicon.ico 200 OK (2ms)
```
Note that Firefox shows the error message below:
`Loading module from “http://127.0.0.1:1999/dist/client.js” was blocked because of a disallowed MIME type (“text/plain”).`
Maybe somehow the server on windows is not using the proper mime types? 
I only have a Windows machine so I do not know whether this happens on Mac/Linux ...etc!

Any idea?

I had a look in RegEdit (Remember I am on Windows) and did not find a default Mime type defined for .js files so I added one. Not sure if this wil work and if it's the right thing to do even if it does work!
![image](https://github.com/partykit/partykit/assets/2162107/ac3bd2f0-dab5-4247-8031-8b0623c19fe4)

**Comment by mehdi-cit** [comment]
BTW, Note in the console log that it did accept normalize.css but not **dist**/client.css
Maybe it has to do with the dist directory?

**Comment by threepointone** [comment]
Thanks so much for filing this, our windows testing is incredibly sparse at the moment 😅 Good catch on the directory path, might be the path separator. I have an idea to fix this, lemme get hold of a windows machine and try it
