### ISSUE TITLE
Add support for custom `logger` (defaulting to `console.log`) for `partysocket` debug mode

### ISSUE THREAD

**Issue by titanism** [partykit/partykit#536]
Right now the console is polluted with `RWS> ...` output due to this:

<https://github.com/partykit/partykit/blob/da3947eb91373cb93410bc339aecf14f327c6cfb/packages/partysocket/src/ws.ts#L335-L339>

An option for `logger` to be passed, defaulting to `false`, but `console.log` (or another logger) could be passed.

**Comment by threepointone** [comment]
Fixed in https://github.com/partykit/partykit/pull/744, pass `debugLogger` in options
