### ISSUE TITLE
Bug: `partysocket` does not return `data` object (as similar to original library it was forked from)

### ISSUE THREAD

**Issue by titanism** [partykit/partykit#538]
Besides #537 there is another core breaking bug that disables us from using `partysocket`.

The issue is that when used with [websocket-as-promised](https://github.com/vitalets/websocket-as-promised), unlike the original fork of `reconnecting-websocket` at <https://github.com/pladaria/reconnecting-websocket>, the `extractMessageData(event)` function of `websocket-as-promised` does not receive the `event.data` property.

This is due to an underlying and breaking change (we consider this a bug) in `partysocket`.

If you make a test project and `const response = await wsp.sendRequest({ some: 'thing' });` you will see that the returned data (if you call `ws.send(...)` with the exact same payload from the server back to the client on this message being received &ndash; it will not return `event.data` in `extractMessageData` option function per the docs at <https://github.com/vitalets/websocket-as-promised#usage-with-ws>

**Comment by threepointone** [comment]
Thanks for reporting! I'll have a look

**Comment by threepointone** [comment]
It's not clear to me that extractMessageData should receive event.data, I'm now of the opinion it should receive `event` itself, so as to be consistent across runtimes. ParrySocket's WebSocket implementation isn't meant to be a clone of the WS module, but a 'standard' WebSocket. I'm going to close this, but I'm happy to discuss.
