### ISSUE TITLE
[Question] Possible to self-host in production?

### ISSUE THREAD

**Issue by josephrocca** [partykit/partykit#551]
I'm wondering if it's possible to (scalably) deploy an app that uses PartyKit outside of PartyKit's cloud? Basically I'm wondering whether I'm locked-in to PartyKit as a server-side provider if I decide to move forward with PartyKit's client library.

Apologies if this is answered elsewhere - I couldn't find any info, and I'm just exploring some possible libraries for a new project, so I haven't looked too deeply into PartyKit's docs yet.

**Comment by threepointone** [comment]
Hiya! Self hosting is on the roadmap, but it'll be a while before we get there. We'll probably get to cloud prem much before that (i.e - hosting on your own cloudflare account).

**Comment by threepointone** [comment]
I'll close this issue, but happy to keep chatting here if you have more questions.

**Comment by josephrocca** [comment]
No problem, thanks for the answer! This was probably already clear from my original post, but my concern is not so much "I would like to self-host" but rather "If I commit to this, I would like to not be locked in." Having the option makes me more comfortable integrating it into my application. So if this is *concretely* (i.e. not "aspirationally") on the roadmap, then that definitely makes me more comfortable with putting in the effort to try integrating this.

Is there any (even very rough) ETA? If not, no worries at all - I completely understand that there are a bunch of different trade-offs to navigate here, and you can't please everybody.
