### ISSUE TITLE
Can't hold a reference to document returned by unstable_getYDoc

### ISSUE THREAD

**Issue by timreinke** [partykit/partykit#552]
Firstly, let me say I've been enjoying playing around with the platform.  I know I'm using an unstable API here, so no complaints on this one from me :) 

**Observed Behavior**
Storing a reference to the doc returned by `unstable_getYDoc` on my `Party.Server` doesn't work because it can return a different document when a client reconnects.

I'm not sure if this is a bug or expected behavior.  This happens with both the local wrangler dev server and when deployed.  Based on the behavior with one connected client vs two, I'm guessing this is tied to how the platform works. 

**Expected Behavior**
The document returned is always the same, or `unstable_getYDoc` (when marked stable) documents this.

**Repro**
With the following server code, I have a client connect using the partykit provider.   The first time the room is started, this works as expected - messages from the server are appended, the client sees them, and they're persisted. 

When the client refreshes, it breaks. The 'active' document changes.  Messages are appended to the old document, but the client doesn't see these since they're syncing with a fresh handle and the changes aren't persisted.

If two clients are connected, this ends up working fine if one refreshes.

```typescript
import type * as Party from "partykit/server";
import * as yparty from "y-partykit";

import * as Y from "yjs";

export default class Server implements Party.Server {
  ydoc: Y.Doc | undefined;
  constructor(readonly party: Party.Party) {}

  async onStart(): Promise<void> {
    this.ydoc = await yparty.unstable_getYDoc(this.party, {
      persist: { mode: "snapshot" },
    });

    setInterval(async () => {
      console.log(
        "setting",
        "ref size",
        (this.ydoc as any).conns.size,
        "get size",
        (
          await yparty.unstable_getYDoc(this.party, {
            persist: { mode: "snapshot" },
          })
        ).conns.size
      );
      this.ydoc?.getArray("messages").insert(0, [`server ${new Date()}`]);
    }, 2000);
  }

  onConnect(
    connection: Party.Connection<unknown>,
    ctx: Party.ConnectionContext
  ): void | Promise<void> {
    console.log(`Connected`, connection.id);
    return yparty.onConnect(connection, this.party, {
      persist: { mode: "snapshot" },
    });
  }
}
```

**Comment by threepointone** [comment]
I think this happened because of a race condition that we had, that should now be fixed in the latest y-partykit. I'm going to close this, but feel free to lemme know if it doesn't work.
