### ISSUE TITLE
Sync across tabs, reduce amount of ws connections

### ISSUE THREAD

**Issue by kof** [partykit/partykit#61]
As a service, it would cause less traffic if messages from multiple tabs would be sent over one websocket connection.

1. This and would reduce the amount of messages being sent to and from multiple tabs and the server
2. Would be faster to see changes across tabs
3. Would work even when you lost connection and your app supports offline-mode

I know this idea from https://logux.io/. It elects the leading tab which holds the websocket connection and instead of creating own connection, it uses postMessage to send the message to the elected tab, which then sends the message to the server and also receives messages from the elected tab instead of its own websocket connection.

If you are in the same room you want sync to happen between all tabs as quickly as possible, without network delay (even though workers are quick, this will be quicker, especially if you are working on a weak connection or you lost connection).

**Comment by threepointone** [comment]
Decided that this should be handled by a lib, like YPartyKitProvider uses broadcast channels
