### ISSUE TITLE
`socket.updateProperties()` overrides `party`

### ISSUE THREAD

**Issue by liorsbg** [partykit/partykit#746]
Check it out here (search for comments that start with BUG):
https://codesandbox.io/p/devbox/partykit-updateproperties-bug-sdc6zw

TLDR, using `usePartySocket` like so:
```
const socket = usePartySocket({
    host: HOST,
    startClosed: true,
    party: "my-non-main-party",
    onMessage(event: MessageEvent<string>) {
      console.log(event.data);
    },
  });
  ```
  
Then calling `socket.updateProperties({ room: room, id: id });` later.
Clients now attempt to connect to `main` party.

**Comment by threepointone** [comment]
great catch!. fixed in https://github.com/partykit/partykit/pull/747, released in `partysocket0.0.25`. Thanks for reporting!
