### ISSUE TITLE
Feature request: Add rawProtocol param for y-partykit

### ISSUE THREAD

**Issue by man-shar** [partykit/partykit#766]
Hello!

We're using y-partykit for our product, but need to "force" the protocol to always be "ws". 

I see an optional `rawProtocol` [option](https://github.com/partykit/partykit/blob/aedaeadecd3fc02fcd183d8dec0165616bc30066/packages/partysocket/src/index.ts#L65-L72) in partysocket, but [didn't see one in y-partykit](https://github.com/partykit/partykit/blob/main/packages/y-partykit/src/provider.ts#L598-L608). 

Wondering if it's feasible to implement that for `y-partykit` as well?

Thanks for the great library!

**Comment by threepointone** [comment]
Sure, that sounds reasonable. PR's up https://github.com/partykit/partykit/pull/767
Can you tell me what your usecase is though? I'm curious.

**Comment by man-shar** [comment]
THANKS!!

For use case: We sometimes have the product deployed in test environments where a VM can be accessed via IP/port, but doesn't have a SSL certificate yet so secure protocols won't work.

This is for our agents product (when deployed in docker): https://defog.ai/blog/agents/

**Comment by threepointone** [comment]
Ah, so this is for when you use it with a non-partykit backend? Fascinating. We have some special handling for websocket messages > 1mb, so it maaay not work in that scenario, but if your messages are below that then it should be fine. 

Released in `y-partykit@0.0.22`. Please test it and let me know if it works as expected!

**Comment by threepointone** [comment]
You can create staging environments with PartyKit btw, eg: `npx partykit deploy --name abc --preview xyz` will deploy it to `xyz.abc.user.partykit.dev` More info here: https://docs.partykit.io/guides/preview-environments/

**Comment by man-shar** [comment]
Yeahhh, but my problem with deploy is that I have `load` and `callback` handlers in my `onConnect`, which read/write from/to a local docker-db 😅 

Re 1mb: That _should_ be fine for a while. We only use Yjs for html serialisation, without any content for the meatier bits  (just attr/id tags).

Loading of the actual content happens later via a separate backend server using those attrs/ids.

**Comment by threepointone** [comment]
Glad you're unblocked. I'll close this for now, but let me know if you have any further issues
