### ISSUE TITLE
Bun not working

### ISSUE THREAD

**Issue by ScreamZ** [partykit/partykit#774]
Hello,

Whenever I use partysocket on bun runtime I get `close` event without any `open`event with `unknown reason`.

https://bun.sh/

Any idea ?

**Comment by threepointone** [comment]
Can you make a repro? Happy to have a look.

**Comment by ScreamZ** [comment]
Hi @threepointone,

https://github.com/ScreamZ/party-socket-bug-bun

I want also to congrats for this package that is working very well in browser/node environment 👏🏻

**Comment by threepointone** [comment]
Thanks for the kind words!

Ok I think I figured this out. Bun currently doesn't accept a connection where `websocket.binaryType = 'blob'`, and `blob` is currently the default for PartySocket. You can workaround this currently with: 

```ts
const socket = new WebSocket("ws://localhost:3000", []);
socket.binaryType = "arraybuffer";
```

I'm closing this issue for now, but happy to continue the conversation.

**Comment by ScreamZ** [comment]
Solved as shown in https://github.com/oven-sh/bun/issues/8721
