### ISSUE TITLE
bug: deploy - windows compatibility issue for wasm files

### ISSUE THREAD

**Issue by a-saq** [partykit/partykit#777]
found a bug on windows when trying to deploy with wasm files included in the project 

`.replace( /\\/g, "/");` is missing in this line [here](https://github.com/partykit/partykit/blob/main/packages/partykit/src/cli.tsx#L861)

**Comment by threepointone** [comment]
fantastic catch. fix incoming.

**Comment by threepointone** [comment]
fixed, available in `partykit@0.0.82`
