### ISSUE TITLE
socket.io clone 

### ISSUE THREAD

**Issue by threepointone** [partykit/partykit#90]

**Comment by jonstuebe** [comment]
Is this a placeholder for `socket.io` support?

**Comment by threepointone** [comment]
not so much for support, but for building a look-alike. I tried building a backend but it was too complicated; I think we could build something that leans into partykit's unique offering. 

(but I'm happy to be proven wrong about building a socket.io backend as well)

**Comment by threepointone** [comment]
https://www.npmjs.com/package/party.io
