### ISSUE TITLE
Crash in node when trying to connect to a websocket that is not available

### ISSUE THREAD

**Issue by sensslen** [partykit/partykit#912]
I'm currently building a distributed system that relys on websocket communcation. One of the nodes may be offline when the control app is started. If this happens, the reconnecting websocket implementation throws an error because the websocket was closed before being opened.

```
Error: TIMEOUT
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: WebSocket was closed before the connection was established
    at WebSocket.close ([...]\node_modules\ws\lib\websocket.js:299:7)
    at _ReconnectingWebSocket._disconnect ([...]\node_modules\partysocket\dist\index.js:422:16)
    at _ReconnectingWebSocket._handleError ([...]\node_modules\partysocket\dist\index.js:454:10)
    at _ReconnectingWebSocket._handleTimeout ([...]\node_modules\partysocket\dist\index.js:413:10)
    at Timeout.<anonymous> ([...]\node_modules\partysocket\dist\index.js:403:20)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose ([...]\node_modules\ws\lib\websocket.js:1041:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Any Idea on how to resolve the issue (or even catch it so that I can retry?)

**Comment by threepointone** [comment]
Does using `.addEventListener("error", ...)` catch the error? (If not, I should fix it to do so)

**Comment by sensslen** [comment]
I'm using 
```
        this._websocket.onerror = (errorevent) => {
            this.log(`websocket error on connection: ${connectionId}\n${errorevent.message}\n${errorevent.error}`);
        };
```
to register for error events and log them. This did not work. Note that I'm using typescript...

**Comment by threepointone** [comment]
Ok I'll have a look at this next week or so. If you can make a repro for me that would be super helpful.

**Comment by sensslen** [comment]
Please find the minimal example here: https://github.com/sensslen/partysocket-error-minimal

**Comment by sensslen** [comment]
@threepointone have you been able to reproduce the issue?

**Comment by sensslen** [comment]
Any news on this issue? Is there something I can help with?

**Comment by FranciscoKnebel** [comment]
Exact same error happening in my use case.
Adding the error event handler triggers it, but it still attempts to close the not-yet established connection, crashing the application.

**Comment by FranciscoKnebel** [comment]
<img width="299" alt="image" src="https://github.com/user-attachments/assets/ef1ce1fa-4537-42bb-ac71-c0ea417b76fc">

So, error is triggered by `this._ws.close(code, reason)` in the _disconnect method:

![image](https://github.com/user-attachments/assets/63a63b14-0a92-469c-a7e2-af5a600c13d3)
 
 What I understand from the error triggered by `ws`, is that we should only attempt to close after the connection is established, so `this._ws.readyState === this.OPEN`, and the error is triggering because we are trying to close while readyState is CONNECTING.

**Comment by abhagsain** [comment]
> we remove the listeners from `this._ws`.

@FranciscoKnebel Did you find any solution for this? We're facing the same issue.
The socket is in the `connecting` state 

<img width="673" alt="image" src="https://github.com/user-attachments/assets/b6f25e6d-3752-4404-bf8d-3ba995313082">

and socket connection is getting closed
<img width="662" alt="image" src="https://github.com/user-attachments/assets/38a3fc1c-53f2-436f-bf80-6eb7b2867232">

**Comment by FranciscoKnebel** [comment]
@abhagsain, for now, while we don't have a fix from the maintainer, we are avoiding this by just forcing reconnection via _restarting the application, so just living with this bug for now.
Any long-standing connection would eventually run into this since we create a lot of sockets. These would happen for connections lasting longer than an 1h, 1.5h, something like that.

The problem is simple and my previous comment shows the error. The module is trying to close the socket without a check for the connection status, and `ws` will not allow an attempt to close the connection while it's trying to connect.

The update needed is to check the status before trying to close. If it's connecting, it needs to wait until it moves from that state before proceeding with trying to disconnect.

**Comment by abhagsain** [comment]
> restarting the application

Hi, can you explain what do you mean by `restarting the application`? Do you ask the user to reload the app or is there something we can do from our end automatically for a better UX?

**Comment by abhagsain** [comment]
> @abhagsain, for now, while we don't have a fix from the maintainer, we are avoiding this by just forcing reconnection via _restarting the application_, so just living with this bug for now. Any long-standing connection would eventually run into this since we create a lot of sockets. These would happen for connections lasting longer than an 1h, 1.5h, something like that.
> 
> The problem is simple and my previous comment shows the error. The module is trying to close the socket without a check for the connection status, and `ws` will not allow an attempt to close the connection while it's trying to connect.
> 
> The update needed is to check the status before trying to close. If it's connecting, it needs to wait until it moves from that state before proceeding with trying to disconnect.

@FranciscoKnebel 

Hi, can you explain what you mean by `restarting the application`? Do you ask the user to reload the app or is there something we can do from our end automatically for a better UX?

**Comment by sensslen** [comment]
@FranciscoKnebel @abhagsain To me it seems @threepointone has pretty much lost interest in this project. What do you guys think of a fork to include the improvements suggested? This bug is pretty much blocking me from really making use of this library....

**Comment by threepointone** [comment]
I've had life issues, sorry it's blocked y'all. You're welcome to fork the project, but no need to presume things about me.

**Comment by sensslen** [comment]
@threepointone sorry to hear that. No harmful intention from my side. I'd gladly work on a PR to fix the issue. I'd much rather keep partysocket than forking.... Would you be up reviewing and if good merging a PR?

**Comment by threepointone** [comment]
I'd appreciate some help! Gimme a few days and lemme come with a broad plan.

**Comment by threepointone** [comment]
I did a release, try with the latest `partysocket` and let me know if this is resolved for everyone?

**Comment by sensslen** [comment]
Thanks - works for me. I checked before submitting the PR
